### ISSUE TITLE
Version State gets reported incorrectly

### ISSUE THREAD

**Issue by dcheremushkin** [tristanlatr/wpscan_out_parse#4]
WPScan starting from version 3.7 reports outdated WordPress version as
`"status": "outdated"` (instead of `"status": "insecure"` as before):

<img width="538" alt="Screen Shot 2021-04-08 at 7 43 43 PM" src="https://user-images.githubusercontent.com/5333431/114065024-e4761580-98a2-11eb-9c7f-5986d35219b7.png">

----

**As a result**, `wpscan_out_parse` reports Version State as `Unknown` (not `Outdated` as expected):
<img width="594" alt="Screen Shot 2021-04-08 at 7 46 18 PM" src="https://user-images.githubusercontent.com/5333431/114065383-48004300-98a3-11eb-8309-b29a37797de3.png">

**Comment by tristanlatr** [comment]
Thanks for the report!

**Comment by tristanlatr** [comment]
Please download the latest version of `wpscan_out_parse` and checkout the magic.

**Comment by dcheremushkin** [comment]
@tristanlatr 👋 Thanks a lot for so fast fix! 🙇 

BTW are you going to release it? So installation via `pip install` will include it? (e.g. on CI)

**Comment by tristanlatr** [comment]
Yes I will create a new release, but first I need to add few tests. 

Can you provide me with a JSON output sample of a scan that was parsed incorrectly ?

In the mean time, you can download the latest version with `pip install git+https://github.com/tristanlatr/wpscan_out_parse.git`
